import React, { useState } from 'react';
import { MessageCircle, X, FileDown } from 'lucide-react';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const ChatBot = ({ data, vesselName, filters }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);

  const generatePDF = async () => {
    try {
      setLoading(true);
      
      // Create a new PDF document
      const pdfDoc = await PDFDocument.create();
      let currentPage = pdfDoc.addPage([600, 800]);
      const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      // Add header
      currentPage.drawText('Defects List', {
        x: 50,
        y: 750,
        size: 24,
        font: boldFont,
        color: rgb(0, 0, 0),
      });

      // Add vessel name and filters
      currentPage.drawText(`Vessel: ${vesselName}`, {
        x: 50,
        y: 720,
        size: 12,
        font: helveticaFont,
      });

      currentPage.drawText(`Generated: ${new Date().toLocaleDateString()}`, {
        x: 50,
        y: 700,
        size: 10,
        font: helveticaFont,
        color: rgb(0.4, 0.4, 0.4),
      });

      // Add table headers
      const headers = ['No.', 'Status', 'Equipment', 'Description', 'Reported'];
      const startY = 660;
      const lineHeight = 20;
      const columnWidths = [40, 80, 120, 200, 80];
      let currentX = 50;

      // Draw header background
      currentPage.drawRectangle({
        x: 45,
        y: startY - 5,
        width: 510,
        height: 25,
        color: rgb(0.95, 0.95, 0.95),
      });

      headers.forEach((header, index) => {
        currentPage.drawText(header, {
          x: currentX,
          y: startY,
          size: 12,
          font: boldFont,
        });
        currentX += columnWidths[index];
      });

      // Add table content
      let currentY = startY - lineHeight;

      data.forEach((item, index) => {
        if (currentY < 50) {
          // Add new page if needed
          currentPage = pdfDoc.addPage([600, 800]);
          currentY = startY;
        }

        const rowData = [
          (index + 1).toString(),
          item['Status (Vessel)'],
          item.Equipments,
          item.Description,
          new Date(item['Date Reported']).toLocaleDateString(),
        ];

        currentX = 50;
        rowData.forEach((text, colIndex) => {
          if (text) {
            currentPage.drawText(text.toString().slice(0, 30) + (text.length > 30 ? '...' : ''), {
              x: currentX,
              y: currentY,
              size: 10,
              font: helveticaFont,
            });
          }
          currentX += columnWidths[colIndex];
        });

        currentY -= lineHeight;
      });

      // Add footer
      currentPage.drawText('Generated by Defects Manager', {
        x: 230,
        y: 30,
        size: 10,
        font: helveticaFont,
        color: rgb(0.4, 0.4, 0.4),
      });

      // Save the PDF
      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `defects-report-${new Date().toISOString().split('T')[0]}.pdf`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setLoading(false);
      setIsOpen(false); // Close chat after successful download
    } catch (error) {
      console.error('Error generating PDF:', error);
      setLoading(false);
    }
  };

  return (
    <>
      {/* Floating Button */}
      <button
        onClick={() => setIsOpen(true)}
        className={`fixed bottom-4 right-4 p-3 rounded-full bg-orange-500 text-white shadow-lg 
        hover:bg-orange-600 transition-all ${isOpen ? 'scale-0' : 'scale-100'}`}
      >
        <div className="flex items-center gap-2">
          <MessageCircle className="h-5 w-5" />
          <span className="text-sm font-medium">Ask AI</span>
        </div>
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div className="fixed bottom-4 right-4 w-80 bg-[#132337] rounded-lg shadow-xl border border-white/10">
          {/* Chat Header */}
          <div className="flex items-center justify-between p-4 border-b border-white/10">
            <div className="flex items-center gap-2">
              <div className="h-8 w-8 rounded-full bg-orange-500 flex items-center justify-center">
                <MessageCircle className="h-4 w-4 text-white" />
              </div>
              <div>
                <h3 className="text-sm font-medium text-white">Ask AI</h3>
                <p className="text-xs text-white/60">Report Generator</p>
              </div>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="text-white/60 hover:text-white"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Chat Content */}
          <div className="p-4">
            <div className="mb-4">
              <p className="text-sm text-white/80 mb-2">
                Hello! I can help you generate a PDF report of your defects list.
              </p>
            </div>

            {/* Action Button */}
            <button
              onClick={generatePDF}
              disabled={loading}
              className="w-full py-2 px-4 bg-orange-500 text-white text-sm rounded-md
              hover:bg-orange-600 transition-all disabled:opacity-50 disabled:cursor-not-allowed
              flex items-center justify-center gap-2"
            >
              {loading ? (
                'Generating PDF...'
              ) : (
                <>
                  <FileDown className="h-4 w-4" />
                  Generate Defects Report
                </>
              )}
            </button>
          </div>
        </div>
      )}
    </>
  );
};

export default ChatBot;
